### PR TITLE
picture: fix reloading images

### LINKED ISSUE #719: Can't change the loaded image
Once loaded, image can't be changed. Snippet (it's a real scenario that happens using C-api):
```
    if (!canvas) return;

    auto picture = tvg::Picture::gen().release();
    picture->load(EXAMPLE_DIR"/test.jpg");
    picture->size(400, 400);
    if (canvas->push(unique_ptr<tvg::Picture>(picture)) != tvg::Result::Success) return;

    picture->load(EXAMPLE_DIR"/test2.jpg");
```

### PR DESCRIPTION
**Pull request by mmaciola**
Calling picture->load after it was already once called resulted in
segmentation fault or memory leak (depending on whether the vector (svg, tvg)
or raster (jpg, png, raw) file was loaded).
This patch adds buffers disposing before loading new image.
To dispose already drawn elements, renderer is kept.

@issue: fixes #719

### CODE REVIEW

File: src/lib/tvgPictureImpl.h [hunk 1]
```diff
@@ -205,6 +219,13 @@ struct Picture::Impl
         if (!loader->read()) return Result::Unknown;
         w = loader->w;
         h = loader->h;
+        if (renderer) dispose(*renderer);
```
Comment (hermet) [inline src/lib/tvgPictureImpl.h:222]: Dismiss the renderer... a bad case in the point of performance wise.
That would be better if we can prevent this scenario ealier from the app.

Comment (mmaciola) [reply src/lib/tvgPictureImpl.h]: Ok. Removed disposing to just checking image is already loaded. If so, return InsufficientCondition.

**Review by hermet — APPROVED** [review]
for safety, we can do this right now but reloading(after sync) will be necessary in the end.
